From: Cole Robinson <crobinso@redhat.com>
Date: Wed, 28 Jul 2010 09:44:13 +0200
Subject: [PATCH] Fix error launching create wizard on qemu:///session

Origin: vendor, http://hg.fedorahosted.org/hg/virt-manager/rev/ea94314da7d5
---
 src/virtManager/uihelpers.py |    6 ++----
 1 files changed, 2 insertions(+), 4 deletions(-)

diff --git a/src/virtManager/uihelpers.py b/src/virtManager/uihelpers.py
index a970ccb..d8fa0dc 100644
--- a/src/virtManager/uihelpers.py
+++ b/src/virtManager/uihelpers.py
@@ -264,9 +264,6 @@ def populate_network_list(net_list, conn):
     bridge_dict = {}
     iface_dict = {}
 
-    def add_row(*args):
-        model.append(build_row(*args))
-
     def build_row(nettype, name, label, is_sensitive, is_running,
                   manual_bridge=False):
         return [nettype, name, label, is_sensitive, is_running, manual_bridge]
@@ -284,7 +281,8 @@ def populate_network_list(net_list, conn):
     # For qemu:///session
     if conn.is_qemu_session():
         nettype = VirtualNetworkInterface.TYPE_USER
-        add_row(nettype, None, pretty_network_desc(nettype), True)
+        r = build_row(nettype, None, pretty_network_desc(nettype), True, True)
+        model.append(r)
         set_active(0)
         return
 
-- 
